### ISSUE TITLE
Improve github actions with a cache of build artifacts

### ISSUE THREAD

**Issue by chrisflatley** [commitd/daze#25]
Would be something like:

```
  - name: Get yarn cache directory path
     id: yarn-cache-dir-path
     run: echo "::set-output name=dir::$(yarn cache dir)"
  - uses: actions/cache@v2
     id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
     with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
  - uses: actions/cache@v2
     with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-
```
